P=
OBJECTS=
CFLAGS = -g -Wall -O3 -std=c99
LDLIBS=
CC=gcc

all: io

io:
epoll: 
process:
mem:
sig:

.PHONY : clean linux

clean :
	-rm io
	-rm epoll
	-rm process
	-rm mem
	-rm sig
	-rm -rf *.dSYM
	-rm -rf iov.bat
	-rm -rf data.bat
	-rm -rf *.out.*
	echo "1th line here!\n2th line here!\n3th line here!\n4th line here!\n5th line here!\n6th line here!\n7th line here!\n8th line here!\n9th line here!" > t.txt
