P=hello
OBJECTS=
CFLAGS = -g -Wall -O3 -std=c99
LDLIBS=
CC=gcc

all: $(P)

$(P):

.PHONY : clean linux

epoll : 

clean :
	-rm $(P)
	-rm epoll
	-rm -rf *.dSYM
	-rm -rf iov.bat
	-rm -rf data.bat
	-rm -rf *.out.*
	echo "1th line here!\n2th line here!\n3th line here!\n4th line here!\n5th line here!\n6th line here!\n7th line here!\n8th line here!\n9th line here!" > t.txt
	
