version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "cslab_mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/var/mongo/log
        volumes:
          - ./.data/mongo/data:/data/db
          - ./.data/mongo/log:/var/mongo/log
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
