version: '3'
services:
    redis:
        image: redis
        volumes:
          - ./.data/redis:/data
          - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
          - 6379:6379
